[project]
name = "cue-provider-utility"
version = "0.1.0"
description = "CLI utility for uploading data to CUE (Cloud Upload Environment)"
authors = [
    {name = "Navaneeth Selvaraj",email = "ns0066@uah.edu"}
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = "^3.10"
dependencies = [
    "click (>=8.2.0,<9.0.0)",
    "httpx[http2] (>=0.28.1,<0.29.0)",
    "aiofiles (>=24.1.0,<25.0.0)",
    "pydantic (>=2.11.4,<3.0.0)",
    "puremagic (>=1.29,<2.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "toml (>=0.10.2,<0.11.0)",
    "python-jose[cryptography] (>=3.4.0,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-cov = "^6.1.1"
pytest-asyncio = "^0.26.0"
pytest-httpx = "^0.35.0"
flake8 = "^7.2.0"
black = "^25.1.0"
mypy = "^1.15.0"
isort = "^6.0.1"

[tool.poetry.scripts]
cue-upload = "cue_provider_utility.main:cli_app"
